config uhttpd 'main'
    list listen_http '0.0.0.0:8080'
    option home '/data/luci/www'
    option cgi_prefix '/cgi-bin'
    option index_page 'index.html'
    option script_timeout '60'
    option network_timeout '30'
    option tcp_keepalive '1'

config cert 'px5g'
    option days '730'
    option bits '2048'
    option country 'CN'
    option state 'GD'
    option location 'Zhongshan'

